export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  TRANSACTION_ALREADY_EXISTS = 'TRANSACTION_ALREADY_EXISTS',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  INVALID_TRANSACTION_STATUS = 'INVALID_TRANSACTION_STATUS',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
}
